import os
import json
import numpy as np
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import matplotlib.pyplot as plt

'''
{
    "conf_id" : 1
}
'''


def get_project_paths():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(base_dir)
    return base_dir, project_root


def get_data(arr_x, arr_y, arr_z, path):
    with open(path, mode="r") as file:
        for line in file:
            parts = line.split()
            if len(parts) < 3:
                continue
            x, y, z = parts[0], parts[1], parts[2]
            arr_x.append(float(x))
            arr_y.append(float(y))
            arr_z.append(float(z))


def draw_pole(folder, fname, color, radius, axes, cylinders_store, project_root):
    folder_path = os.path.join(project_root, folder)
    if not os.path.isdir(folder_path):
        return
    if not fname.lower().endswith(".txt"):
        return
    x, y, z = [], [], []
    get_data(x, y, z, os.path.join(folder_path, fname))
    for i in range(len(x) - 1):
        start = np.array([x[i], y[i], z[i]])
        end = np.array([x[i + 1], y[i + 1], z[i + 1]])
        axis = end - start
        length = np.linalg.norm(axis)
        if length == 0:
            continue
        axis = axis / length
        perp1 = np.array([0.0, 1.0, 0.0])
        perp2 = np.array([0.0, 0.0, 1.0])
        theta = np.linspace(0.0, 2.0 * np.pi, 16, endpoint=True)
        circle = radius * (np.cos(theta)[:, None] * perp1 + np.sin(theta)[:, None] * perp2)
        bottom_circle = start + circle
        top_circle = end + circle
        cylinders_store.append((bottom_circle, top_circle, color))
        verts = []
        for j in range(len(theta) - 1):
            verts.append(
                [
                    bottom_circle[j],
                    bottom_circle[j + 1],
                    top_circle[j + 1],
                    top_circle[j],
                ]
            )
        verts.append(
            [
                bottom_circle[-1],
                bottom_circle[0],
                top_circle[0],
                top_circle[-1],
            ]
        )
        axes.add_collection3d(Poly3DCollection(verts, facecolors=color, edgecolor="none", alpha=0.1))
        axes.add_collection3d(Poly3DCollection([bottom_circle], facecolors=color, edgecolor="none", alpha=0.1))
        axes.add_collection3d(Poly3DCollection([top_circle], facecolors=color, edgecolor="none", alpha=0.1))


def export_obj(path, cylinders):
    """
    Экспорт в OBJ-формате с поддержкой цветов через материалы (MTL)
    """
    # Определяем цвета для разных объектов
    color_map = {
        'r': (1.0, 0.0, 0.0),      # красный для Bufer
        'b': (0.0, 0.0, 1.0),      # синий для Fractal
        'g': (0.0, 1.0, 0.0),      # зелёный (больше не используется)
    }

    vertices = []
    material_faces = []

    # Создаем MTL файл с определениями материалов
    mtl_path = path.replace('.obj', '.mtl')
    os.makedirs(os.path.dirname(path), exist_ok=True)

    with open(mtl_path, 'w') as mtl_file:
        mtl_file.write("# MTL file generated by draw_fbx.py\n")
        for color_name, rgb in color_map.items():
            mtl_file.write(f"\nnewmtl material_{color_name}\n")
            mtl_file.write(f"Ka {rgb[0]} {rgb[1]} {rgb[2]}\n")  # ambient
            mtl_file.write(f"Kd {rgb[0]} {rgb[1]} {rgb[2]}\n")  # diffuse
            mtl_file.write(f"Ks 0.2 0.2 0.2\n")                 # specular
            mtl_file.write("Ns 32\n")                           # shininess
            mtl_file.write("d 1.0\n")                           # opacity
            mtl_file.write("illum 2\n")                         # illumination model

    # Экспортируем цилиндры с разными цветами
    for bottom, top, color in cylinders:
        n = bottom.shape[0]
        base = len(vertices) + 1

        # Добавляем вершины
        for v in bottom:
            vertices.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
        for v in top:
            vertices.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")

        material_name = f"material_{color}"

        # Добавляем грани цилиндра
        cylinder_faces = []
        for j in range(n - 1):
            cylinder_faces.append(f"f {base + j} {base + j + 1} {base + n + j + 1} {base + n + j}")
        cylinder_faces.append(f"f {base + n - 1} {base + 0} {base + n + 0} {base + n + n - 1}")

        material_faces.append((material_name, cylinder_faces))

    # Записываем OBJ файл
    with open(path, 'w') as f:
        f.write(f"mtllib {os.path.basename(mtl_path)}\n\n")
        f.write("\n".join(vertices) + "\n\n")

        # Записываем грани по группам материалов
        for material_name, face_list in material_faces:
            f.write(f"g {material_name}\n")
            f.write(f"usemtl {material_name}\n")
            f.write("\n".join(face_list) + "\n\n")

    print(f"Экспортирован OBJ файл: {path}")
    print(f"Экспортирован MTL файл: {mtl_path}")


def main():
    base_dir, project_root = get_project_paths()

    fig = plt.figure(figsize=(12, 8))
    axes = fig.add_subplot(projection="3d")
    axes.set_xlabel("x")
    axes.set_ylabel("y")
    axes.set_zlabel("z")
    axes.set_xlim(0, 1000)
    axes.set_ylim(-500, 500)
    axes.set_zlim(-500, 500)

    # Читаем упрощённый JSON с conf_id
    config_file = os.path.join(base_dir, "config.json")   # или другое имя
    with open(config_file, mode="r") as file:
        data = json.load(file)
        conf_id = data["conf_id"]

    # Загружаем конфигурацию эксперимента
    config_path = os.path.join(project_root, "Sowing", "Config", f"conf_{conf_id}.json")
    with open(config_path, mode="r") as file:
        data = json.load(file)
        bufer_id = data["Bufer"]
        fractal_id = data["Fractal"]
        radius = data["Size"]

    cylinders = []

    # Отрисовка буфера и фрактала
    draw_pole(os.path.join("Sowing", "Bufer"), f"Bufer_{bufer_id}.txt", "r", radius, axes, cylinders, project_root)
    draw_pole(os.path.join("Sowing", "Fractal"), f"Pole_{fractal_id}.txt", "b", radius, axes, cylinders, project_root)

    # Экспорт в OBJ
    output_dir = os.path.join(project_root, f"images/Fractal_{conf_id}")
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, f"Fractal_{conf_id}_3d.obj")
    export_obj(output_path, cylinders)

    plt.title(f"Configuration {conf_id}")
    # plt.show()   # закомментировано


if __name__ == "__main__":
    main()